### ISSUE TITLE
Check Status of Pizza

### ISSUE THREAD

**Issue by TomazMartins** [fabraz/gepetohut#2]
# Check Status of Pizza
## User Story

_I, as a customer, I want to check the status of pizza, for sure me that everything is being done on time._
(_Eu, como cliente, eu quero verificar o status da pizza, para certificar-me de que tudo está sendo feito dentro do prazo._)
## Tasks
- [ ] Utilizar a permissão de Gerente.
- [ ] Criar tela de Gerência.
- [ ] Mudança dinâmica de status no banco e nas telas: gerente e cliente (Dica: utilizar AJAX).
