### ISSUE TITLE
Define initial Product Backlog

### ISSUE THREAD

**Issue by TomazMartins** [fabraz/gepetohut#25]
# Define Initial Product Backlog
## User Story

_I, as Scrum master, I want to set an initial backlog to determine time and effort required to complete the project._
(_Eu, como scrum master, eu quero definir um backlog inicial para averiguar tempo e esforço necessários para finalizar o projeto._)
## Tasks
- [x] Meet with team and discuss project scope.
- [ ] Validate with teacher (PO) the product backlog.
- [ ] Make changes requested by the teacher (PO).
