### ISSUE TITLE
Define Roadmap

### ISSUE THREAD

**Issue by TomazMartins** [fabraz/gepetohut#26]
# Define Roadmap
## User Story

_I, as scrum master, I want a roadmap to guide the development of the team._
(_Eu, como scrum master, eu quero um roadmap para guiar o desenvolvimento da equipe._)
## Tasks

[Once the User Story is selected to enter the team backlog tasks must be derived].
- [x] Perform Planning Poker with team.
- [x] Analyze the amount of user points and set an initial planning.
- [x] Observe with team the distribution of user points in sprints.
- [x] Make corrections evaluated by the team during the analysis of points distribution.
