### ISSUE TITLE
Configuration of Environment

### ISSUE THREAD

**Issue by TomazMartins** [fabraz/gepetohut#28]
# Configuration of Environment
## User Story

_I, as a developer, I want to set up the development environment to avoid different environments among team members._
(_Eu, como desenvolvedor, eu quero configurar o ambiente de desenvolvimento para evitar ambientes diferentes entre os membros da equipe._)
## Tasks

Member of Team: José Pedro:
- [x] Install Ubuntu 14.04 or similar.
- [x] Install Ruby, version 2.1.2.
- [x] Set a gemset for the project call **gepetohut**.
- [x] Install Rails, version 4.1.0 in gemset.

Member of Team: Maxwell:
- [x] Install Ubuntu 14.04 or similar.
- [x] Install Ruby, version 2.1.2.
- [x] Set a gemset for the project call **gepetohut**.
- [x] Install Rails, version 4.1.0 in gemset.

Member of Team: Thaiane:
- [x] Install Ubuntu 14.04 or similar.
- [x] Install Ruby, version 2.1.2.
- [x] Set a gemset for the project call **gepetohut**.
- [x] Install Rails, version 4.1.0 in gemset.

Member of Team: Tomáz:
- [x] Install Ubuntu 14.04 or similar.
- [x] Install Ruby, version 2.1.2.
- [x] Set a gemset for the project call **gepetohut**.
- [x] Install Rails, version 4.1.0 in gemset.
