### ISSUE TITLE
Define Tools

### ISSUE THREAD

**Issue by TomazMartins** [fabraz/gepetohut#29]
# Define Tools
## User Story

_I, as a developer, I want to define what tools will be used to initiate studies and environment configuration._
(_Eu, como desenvolvedor, eu quero definir quais as ferramentas serão usadas para iniciar estudos e configuração do ambiente._)
## Tasks

[Once the User Story is selected to enter the team backlog tasks must be derived].
- [x] Define which language to use.
- [x] Define what framework of web application to use.
- [x] Define what continuous integration tool to use.
- [x] Define testing tools to use.
- [x] Define which versions of using of this tools.
